version: "3.3"
services:
  backend_spring:
    # image: openjdk:11-jdk
    build: ./greedytown
    container_name: backend_spring
    env_file:
      - ./backend.env
    ports:
      - 8080:8080
    command: java -jar app.jar # chmod +x ./gradlew && ./gradlew bootJar && 
